
const restaurantList = [
    {
        id: "1001",
        name: "Santosh Family Dhaba",
        recipe: "Tomato Soup",
        rating: "4.0",
        price: "₹300 for two",
        deliveryTime: "22 MINS",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/mkcibe6x1ychvzjkywxk",
    },
    {
        id: "1002",
        name: "Cafe Niloufer",
        recipe: "Maska Bun",
        rating: "4.5",
        price: "₹400 for two",
        deliveryTime: "32 MINS",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/dc9t0kiq7lhsd3pndohf",
    },
    {
        id: "1003",
        name: "Fresh Foods",
        recipe: "Crispy Corn",
        rating: "4.5",
        price: "₹560 for two",
        deliveryTime: "32 MINS",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/dwqb8nhiop8fvqya0alq",
    },
    {
        id: "1004",
        name: "Grameen Kulfi",
        recipe: "Sitaphal Stick Kulfi",
        rating: "4.6",
        price: "₹120 for two",
        deliveryTime: "18 MINS",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/vu0thsifji9wgfuzfmic",
    },
    {
        id: "1005",
        name: "Subbayya Gari Hotel",
        recipe: "Butta Bojanam",
        rating: "4.0",
        price: "₹300 for two",
        deliveryTime: "24 MINS",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/iwtocxqjtu57vc7l52h9",
    },
    {
        id: "1006",
        name: "Utsav Vegetarian",
        recipe: "Kaju Paneer Biryani",
        rating: "4.1",
        price: "₹300 for two",
        deliveryTime: "32 MINS",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/y2lkcxxax3794vepe2se",
    },
    {
        id: "1007",
        name: "Vadilal Icecream",
        recipe: "Ice Cream,Desserts",
        rating: "4.5",
        price: "₹250 for two",
        deliveryTime: "30 MINS",
        image: "https://b.zmtcdn.com/data/pictures/chains/0/19428760/cbaa80e5dd27d9d6cb546a94e33594cc_o2_featured_v2.jpg",
    },
    {
        id: "1008",
        name: "Gourmet Haven",
        recipe: "Classic Margherita Pizza",
        rating: "4.7",
        price: "₹400 for two",
        deliveryTime: "35 MINS",
        image: "https://b.zmtcdn.com/data/pictures/8/20142548/928a64fea683b4b5406f093cbcc9c646_o2_featured_v2.jpg?output-format=webp",
    },
    {
        id: "1009",
        name: "Taste Buds",
        recipe: "Hawaiian Pizza",
        rating: "4.2",
        price: "₹350 for two",
        deliveryTime: "28 MINS",
        image: "https://media.istockphoto.com/id/1349383878/photo/hawaiian-pizza-with-ham-and-pineapple.jpg?s=612x612&w=is&k=20&c=fhbTavVuQCEAwCdOJdUbjA23B4FPZQlp_K7qrjfllz4=",
    },
    {
        id: "1010",
        name: "Burger Delight",
        recipe: "Cheeseburger with Fries",
        rating: "4.3",
        price: "₹300 for two",
        deliveryTime: "25 MINS",
        image: "https://media.istockphoto.com/id/1309352410/photo/cheeseburger-with-tomato-and-lettuce-on-wooden-board.jpg?s=612x612&w=0&k=20&c=lfsA0dHDMQdam2M1yvva0_RXfjAyp4gyLtx4YUJmXgg=",
    },
    {
        id: "1011",
        name: "Mcdonald's",
        recipe: "Burger",
        rating: "4.8",
        price: "₹600 for two",
        deliveryTime: "40 MINS",
        image: "https://b.zmtcdn.com/data/pictures/4/2300034/b1edd883d05e7d3d693f1d3e88558521_o2_featured_v2.jpg",
    },
    {
        id: "1012",
        name: "Kake Di Hatti",
        recipe: "North Indian",
        rating: "4.6",
        price: "₹500 for two",
        deliveryTime: "30 MINS",
        image: "https://b.zmtcdn.com/data/pictures/9/20619329/d12f2c33ac7d347786ae3444d00b674d_featured_v2.jpg",
    }
];
   

  export default restaurantList